name: sample

on:
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
    
    steps:
      - name: Print Start Message
        run: echo "Starting CI/CD Pipeline..."

      - name: Checkout Repository
        uses: actions/checkout@v2